### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by XL-Reaper**
I've created a simple docker-compose setup that will bring up WolfBot with MongoDB & the default configuration.
All you have to do before is copy/rename the file configLocal-Docker.ts to configLocal.ts - and adjust it according to your needs (API etc.). The MongoDB URl is correct! It is just referencing the container internal name.

After a "docker-compose up" you should be able to reach your WolfBot at http://your.docker.host:8331/index.html?apiKey=SomeAPIkey

There are some dirty hacks in the Dockerfile to get this working (disabling Typescript watch mode, forcing clean exit codes although Typescript reports errors). To be able to clear these, the main maintainer would have to clean up the code a bit more :)

### CODE REVIEW

**Comment by Ekliptor** [comment]
thx for your work.
A few questions before we merge this:

1. Why do you provide a separate `configLocal-docker.ts `?
2. Why are you editing `watch` mode in `tsconfig.json`? You can just run `tsc --watch false` to override the value in the file.

**Comment by XL-Reaper** [comment]
1. That is just a sample file and not really needed. It's just to demonstrate how the mongoUrl should look like.
2. I did not find that option in the man page, there was just a setting to turn on watch mode. 
I've updated the Dockerfile, thanks for the hint.

**Comment by Ekliptor** [comment]
it's merged with some changes:
- not running tsc as root
- removed the new config file and use `ENV WOLF_CONTAINER=docker` to change the `mongoUrl`

**Comment by XL-Reaper** [comment]
Perfect :) This makes it even better

**Pull request merged**
